openapi: 3.0.0
info:
  version: '0.1'
  title: 'DigitalTwinManagementApi'
  description: 'Core Management Api for a Digital Twin'
paths:
  /identifier:
    get:
      tags:
        - "Management"
      description: "Retrieve the digital twin identifier"
      operationId: getIdentifier
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/digitalTwinIdentifier'
  /addLink:
    post:
      tags:
        - "Management"
        - "SemanticLink"
      description: "Add a link to another Digital Twin"
      operationId: addLinkToAnotherDigitalTwin
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/linkToAnotherDigitalTwin"
      responses:
        '200':
          description: "link successfully added"
        '400':
          description: "bad request"
        '500':
          description: "server error"
  /links:
    get:
      tags:
        - "Management"
        - "SemanticLink"
      description: "Retrieve all links to other digital twins"
      operationId: getAllLinkToOtherDigitalTwins
      responses:
        '200':
          description: "ok"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/links"
        '500':
          description: "server error"

  /links/{linkId}:
    delete:
      tags:
        - "Management"
        - "SemanticLink"
      description: "Delete the link to antoher digital twin passing the link identifier"
      operationId: deleteLink
      parameters:
        - $ref: "#/components/parameters/link-id-param"
      responses:
        '204':
          description: "link successfully deleted"
        '404':
          description: "link not found"
        '500':
          description: "server error"

  /shutdown:
    post:
      tags:
        - "Management"
      description: "Notify the digital twin to start the shutdown procedure"
      operationId: shutdownDigitalTwin
      responses:
        '201':
          description: "Shutdown Process Executed"
components:
  parameters:
    link-id-param:
      in: path
      name: "linkId"
      description: "identifier of the link to another digital twin"
      required: true
      schema:
        $ref: "#/components/schemas/linkIdentifier"

  schemas:
    digitalTwinIdentifier:
      type: string

    linkIdentifier:
      type: string

    linkToAnotherDigitalTwin:
      type: object
      required:
        - id
        - otherDigitalTwin
        - semantic
      properties:
        id:
          $ref: "#/components/schemas/linkIdentifier"
        otherDigitalTwin:
          $ref: "#/components/schemas/digitalTwinIdentifier"
        semantic:
          type: object

    links:
      type: array
      items:
        allOf:
          - $ref: "#/components/schemas/linkToAnotherDigitalTwin"