/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hospitaldigitaltwins

class App {
    companion object {
        fun startServices() {
            //PatientVerticleStarter.deployVerticle()
        }
    }

    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
    App.startServices()
}
